

const Moviedetails = [
    {
    id:1,
    title:'Spiderman accross the spider verse',
    poster:'spidermanposter.jpg',
    cover:'spidermancover.jpeg',
    ratings:'8.9/10',
    categary:'Animation',
    discription:'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.',
    directors:'Joaquim Dos SantosKemp PowersJustin K. Thompson',
    duration:'2h 20m',
    cast:[{name:'Shameik Moore-Miles Morales(voice)',img:'shamik.jfif'},{name:'hailey stephend',img:'hailee.jfif'},{name:'Luna Lauren Velez',img:'luna.jfif'},
   {name:'Jake Johnson',img:'jake.jfif'},{name:'Oscar Isaac',img:'oscar.jfif'}],
    },{
        id:2,
        title:'Adipurush',
        poster:'adiposter.jpg',
        cover:'adicover.jpeg',
        ratings:'3.7/10',
        categary:'Advanture',
        discription:'Adaptation of Indian mythology that depicts the triumph of good over evil.',
        directors:'Om raut',
        duration:'2h 50m',
        cast:[{name:'Kriti Sanon',img:'kriti.jfif'},{name:'Prabhas',img:'Prabhas.jfif'},{name:'Vatsal Sheth',img:'VatsalSheth.jfif'},
       {name:'Saif Ali Khan',img:'SaifAliKhan.jfif'},{name:'Sunny Singh',img:'SunnySingh.jfif'}],
        },
        {
            id:3,
            title:'Avatar the way of water',
            poster:'avatarposter.jpg',
            cover:'avatarcover.png',
            ratings:'7.6/10',
            categary:'fantasy',
            discription:'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Navi race to protect their home.',
            directors:'James cameron',
            duration:'3h 12m',
            cast:[{name:'Sam Worthington',img:'SamWorthington.jfif'},{name:'ZoeSaldana',img:'ZoeSaldana.jfif'},{name:'StephenLang',img:'StephenLang.jfif'},
           {name:'Cliff Curtis',img:'CliffCurtis.jfif'},{name:'KateWinslet',img:'KateWinslet.jfif'}],
            },
            {
                id:4,
                title:'The flash',
                poster:'flashposter.jpg',
                cover:'flashcover.jpeg',
                ratings:'3.7/10',
                categary:'Advanture',
                discription:'Adaptation of Indian mythology that depicts the triumph of good over evil.',
                directors:'Om raut',
                duration:'2h 50m',
                cast:[{name:'Kriti Sanon',img:'kriti.jfif'},{name:'Prabhas',img:'Prabhas.jfif'},{name:'Vatsal Sheth',img:'VatsalSheth.jfif'},
               {name:'Saif Ali Khan',img:'SaifAliKhan.jfif'},{name:'Sunny Singh',img:'SunnySingh.jfif'}],
                },
                {   id:5,
                    title:'Guardian of the galaxy',
                    poster:'guardianposter.jpg',
                    cover:'guardiancover.jpeg',
                    ratings:'3.7/10',
                    categary:'Advanture',
                    discription:'Adaptation of Indian mythology that depicts the triumph of good over evil.',
                    directors:'Om raut',
                    duration:'2h 50m',
                    cast:[{name:'Kriti Sanon',img:'kriti.jfif'},{name:'Prabhas',img:'Prabhas.jfif'},{name:'Vatsal Sheth',img:'VatsalSheth.jfif'},
                   {name:'Saif Ali Khan',img:'SaifAliKhan.jfif'},{name:'Sunny Singh',img:'SunnySingh.jfif'}],
                    },
                    {   id:6,
                        title:'Evil dead rise',
                        poster:'evilposter.jpg',
                        cover:'evilcover.jpeg',
                        ratings:'3.7/10',
                        categary:'Advanture',
                        discription:'Adaptation of Indian mythology that depicts the triumph of good over evil.',
                        directors:'Om raut',
                        duration:'2h 50m',
                        cast:[{name:'Kriti Sanon',img:'kriti.jfif'},{name:'Prabhas',img:'Prabhas.jfif'},{name:'Vatsal Sheth',img:'VatsalSheth.jfif'},
                       {name:'Saif Ali Khan',img:'SaifAliKhan.jfif'},{name:'Sunny Singh',img:'SunnySingh.jfif'}],
                        },
                        {   id:7,
                            title:'After',
                            poster:'afterposter.jpg',
                            cover:'aftercover.png',
                            ratings:'3.7/10',
                            categary:'Advanture',
                            discription:'Adaptation of Indian mythology that depicts the triumph of good over evil.',
                            directors:'Om raut',
                            duration:'2h 50m',
                            cast:[{name:'Kriti Sanon',img:'kriti.jfif'},{name:'Prabhas',img:'Prabhas.jfif'},{name:'Vatsal Sheth',img:'VatsalSheth.jfif'},
                           {name:'Saif Ali Khan',img:'SaifAliKhan.jfif'},{name:'Sunny Singh',img:'SunnySingh.jfif'}],
                            },
                            {   id:8,
                                title:'Mamannan',
                                poster:'mamaposter.jpg',
                                cover:'mamacover.jpeg',
                                ratings:'3.7/10',
                                categary:'Advanture',
                                discription:'Adaptation of Indian mythology that depicts the triumph of good over evil.',
                                directors:'Om raut',
                                duration:'2h 50m',
                                cast:[{name:'Kriti Sanon',img:'kriti.jfif'},{name:'Prabhas',img:'Prabhas.jfif'},{name:'Vatsal Sheth',img:'VatsalSheth.jfif'},
                               {name:'Saif Ali Khan',img:'SaifAliKhan.jfif'},{name:'Sunny Singh',img:'SunnySingh.jfif'}],
                                },
                                {   id:9,
                                    title:'Antman quantum mania',
                                    poster:'quantamposter.jpg',
                                    cover:'quantamcover.jpeg',
                                    ratings:'3.7/10',
                                    categary:'Advanture',
                                    discription:'Adaptation of Indian mythology that depicts the triumph of good over evil.',
                                    directors:'Om raut',
                                    duration:'2h 50m',
                                    cast:[{name:'Kriti Sanon',img:'kriti.jfif'},{name:'Prabhas',img:'Prabhas.jfif'},{name:'Vatsal Sheth',img:'VatsalSheth.jfif'},
                                   {name:'Saif Ali Khan',img:'SaifAliKhan.jfif'},{name:'Sunny Singh',img:'SunnySingh.jfif'}],
                                    },
                                ]

export default Moviedetails